apiVersion: apps/v1
kind: Deployment
metadata:
  name: profitx-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profitx-backend
  template:
    metadata:
      labels:
        app: profitx-backend
    spec:
      containers:
        - name: backend
          image: your-backend-image
          ports:
            - containerPort: 5000
          env:
            - name: OANDA_API_KEY
              value: your_oanda_api_key
            - name: JWT_SECRET_KEY
              value: supersecretkey
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: profitx-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
